version: "3.1"

services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=letseatinthai
      - MYSQL_USER=letseatinthai
      - MYSQL_PASSWORD=s6AeHwCq6MxHwjNBZfHmLA4udZ
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    image: itoph2018
    depends_on:
      - mariadb
      - redis
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=openhouse_2018
      - URLROOT=http://localhost
      - SITENAME=IT Ladkrabang Openhouse 2018
      - MAIL_HOST=localhost
      - MAIL_USER=root
      - MAIL_PASS=iamsosexy
      - MAIL_SENDER=openhouse@it.kmtil.ac.th
      - MAIL_SENDER_NAME=IT Ladkrabang Openhouse 2018
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/usr/share/nginx/html